export { MagicTextEditor } from './components/MagicTextEditor'
export type { MagicTextEditorProps, RulerConfig } from './components/MagicTextEditor'
export { RulerExtension, DEFAULT_MARGINS } from './extensions/RulerExtension'
export type { PageMargins } from './extensions/RulerExtension'
export { VerticalRuler } from './components/Ruler/VerticalRuler'
export { Toolbar, ToolbarButton, ToolbarDivider, VariableDropdown, TTSPopover } from './components/Toolbar'
export { TTSMarkExtension } from './extensions/TTSMarkExtension'
export { TTSDocumentReader } from './components/TTSDocumentReader'
export { extractTTSSegments } from './utils/extractTTSSegments'
export { useTTSSegments } from './hooks/useTTSSegments'
export { registerLocale, resolveTranslations, useTranslations, en, es } from './i18n'
export type { TTSAttrs, TTSMark, TTSPlayPayload, TTSSegment, JSONContent, ContentType, Variable, VariableType, Translations, PartialTranslations } from './types'
