import type { PageBackground } from './types';

export const pageBackgrounds: PageBackground[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Your current theme paper color',
    category: 'page-background',
    unlockMethod: 'free',
    cssValue: null,
    thumbnail: 'var(--paper-bg)',
    tags: ['minimal', 'default'],
  },
  {
    id: 'parchment',
    name: 'Parchment',
    description: 'Warm vintage parchment paper',
    category: 'page-background',
    unlockMethod: 'free',
    cssValue: 'linear-gradient(160deg, #f5e6c2 0%, #e8d49e 100%)',
    thumbnail: '#f0dca8',
    textColor: '#3a2510',
    highlightColor: 'rgba(170, 100, 15, 0.32)',
    sentenceHoverColor: 'rgba(170, 100, 15, 0.16)',
    tags: ['warm', 'vintage'],
  },
  {
    id: 'midnight-slate',
    name: 'Midnight Slate',
    description: 'Deep blue-gray for late night reading',
    category: 'page-background',
    unlockMethod: 'purchase',
    price: 100,
    cssValue: 'linear-gradient(160deg, #1e2433 0%, #161b27 100%)',
    thumbnail: '#1e2433',
    textColor: '#bfcce0',
    highlightColor: 'rgba(75, 115, 175, 0.48)',
    sentenceHoverColor: 'rgba(75, 115, 175, 0.22)',
    tags: ['dark', 'night'],
  },
  {
    id: 'warm-linen',
    name: 'Warm Linen',
    description: 'Soft linen-white for comfortable reading',
    category: 'page-background',
    unlockMethod: 'purchase',
    price: 100,
    cssValue: 'linear-gradient(160deg, #faf7f0 0%, #f0ebe0 100%)',
    thumbnail: '#f5f0e8',
    textColor: '#28201a',
    highlightColor: 'rgba(155, 105, 35, 0.28)',
    sentenceHoverColor: 'rgba(155, 105, 35, 0.14)',
    tags: ['warm', 'minimal', 'light'],
  },
  {
    id: 'scholars-amber',
    name: "Scholar's Amber",
    description: 'Antique amber tone for focused study',
    category: 'page-background',
    unlockMethod: 'achievement',
    achievementId: 'bookworm',
    cssValue: 'linear-gradient(160deg, #2a1f0e 0%, #1d1608 100%)',
    thumbnail: '#2a1f0e',
    textColor: '#d4b070',
    highlightColor: 'rgba(185, 135, 45, 0.48)',
    sentenceHoverColor: 'rgba(185, 135, 45, 0.22)',
    tags: ['dark', 'vintage', 'rare'],
  },
];
