import type { SoundBackground } from './types';
import rainWindowUrl from '../../assets/sounds/rain-window.mp3';

export const soundBackgrounds: SoundBackground[] = [
  {
    id: 'rain-window',
    name: 'Rain on Window',
    description: 'Soft droplets against a windowpane',
    category: 'sound-background',
    unlockMethod: 'free',
    streamUrl: rainWindowUrl,
    loop: true,
    available: true,
    tags: ['rain', 'calm', 'focus'],
  },
  {
    id: 'cafe-murmur',
    name: 'Café Murmur',
    description: 'Gentle café ambience with distant chatter',
    category: 'sound-background',
    unlockMethod: 'purchase',
    price: 120,
    streamUrl: 'https://cdn.nhexa.cl/assets/sounds/cafe-murmur.mp3',
    loop: true,
    tags: ['café', 'social', 'focus'],
  },
  {
    id: 'ancient-forest',
    name: 'Ancient Forest',
    description: 'Birds and rustling leaves in a deep forest',
    category: 'sound-background',
    unlockMethod: 'purchase',
    price: 120,
    streamUrl: 'https://cdn.nhexa.cl/assets/sounds/ancient-forest.mp3',
    loop: true,
    tags: ['nature', 'forest', 'calm'],
  },
  {
    id: 'ocean-tides',
    name: 'Ocean Tides',
    description: 'Rhythmic waves on a quiet shore',
    category: 'sound-background',
    unlockMethod: 'purchase',
    price: 120,
    streamUrl: 'https://cdn.nhexa.cl/assets/sounds/ocean-tides.mp3',
    loop: true,
    tags: ['ocean', 'nature', 'relaxing'],
  },
  {
    id: 'crackling-hearth',
    name: 'Crackling Hearth',
    description: 'Warm fireplace on a winter night',
    category: 'sound-background',
    unlockMethod: 'purchase',
    price: 150,
    streamUrl: 'https://cdn.nhexa.cl/assets/sounds/crackling-hearth.mp3',
    loop: true,
    tags: ['fire', 'cozy', 'warm'],
  },
  {
    id: 'northern-winds',
    name: 'Northern Winds',
    description: 'Haunting winds from the far north',
    category: 'sound-background',
    unlockMethod: 'achievement',
    achievementId: 'explorer',
    streamUrl: 'https://cdn.nhexa.cl/assets/sounds/northern-winds.mp3',
    loop: true,
    tags: ['wind', 'atmospheric', 'rare'],
  },
];
